baseURL: https://cdk8s.io/
languageCode: en-us
title: CDK for Kubernetes
googleAnalytics: UA-166333129-1

disableKinds:
- taxonomy
- taxonomyTerm

markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  summary: Define Kubernetes apps and components using familiar languages
  subtitle: Cloud Development Kit for Kubernetes
  description: |
    **cdk8s** is an open-source software development framework for defining Kubernetes
    applications and reusable abstractions using familiar programming languages
    and rich object-oriented APIs. **cdk8s** apps synthesize into standard
    Kubernetes manifests which can be applied to any Kubernetes cluster.

  features:
    everywhere:
      title: Works with Kubernetes everywhere
      details: |
        You can use cdk8s to define applications for any Kubernetes cluster
        running anywhere, including any cloud or on-premises. cdk8s runs locally
        in your development environment and produces standard Kubernetes YAML
        that can be applied to any cluster
    languages:
      title: Language support
      details: |
        cdk8s lets you define applications using Typescript, JavaScript, and
        Python. Support for more languages, including Go is coming soon
    imports:
      title: Supports core Kubernetes objects and custom resources
      details: |
        You can import objects from any Kubernetes API version and custom
        resource definitions to use with cdk8s. This makes it easy to use cdk8s
        to easily write entire Kubernetes applications and keep them up to date
        as applications change
    gitops:
      title: Deploy through GitOps
      details: |
        cdk8s works great with a GitOps workflow, making it easy to see changes
        as you modify your configuration and between API versions. Simply use
        the cdk8s to synthesize new YAML configuration files and commit them to
        your git repo
    community:
      title: Community-driven
      details: |
        We are building cdk8s for any developer who uses Kubernetes to define
        their applications. We encourage contributions of any type, from fixing
        typos to building new features. Our goal is that cdk8s becomes an
        official CNCF sandbox project that the entire community can use

  footer_title: Define imperative, deploy declarative
  footer_subtitle: |
    The power of imperative languages combined with the robustness of
    declarative desired state

  links:
    getting_started: https://github.com/awslabs/cdk8s/blob/master/README.md#getting-started
    getting_started_python: https://github.com/awslabs/cdk8s/blob/master/docs/getting-started/python.md
    getting_started_typescript: https://github.com/awslabs/cdk8s/blob/master/docs/getting-started/typescript.md
    license: https://github.com/awslabs/cdk8s/blob/master/LICENSE
